@Library('Shared') _
pipeline {
    agent { label 'worker' }

    parameters {
        string(name: 'FRONTEND_DOCKER_TAG', defaultValue: '', description: 'Frontend Docker tag of the image built by the CI job')
        string(name: 'BACKEND_DOCKER_TAG', defaultValue: '', description: 'Backend Docker tag of the image built by the CI job')
    }

    stages {

        stage("Workspace cleanup") {
            steps {
                cleanWs()
            }
        }

        stage('Git: Code Checkout') {
            steps {
                code_checkout("https://github.com/YR55/Wanderlust-Mega-Project.git", "main")
            }
        }

        stage('Verify: Docker Image Tags') {
            steps {
                echo "FRONTEND_DOCKER_TAG: ${params.FRONTEND_DOCKER_TAG}"
                echo "BACKEND_DOCKER_TAG: ${params.BACKEND_DOCKER_TAG}"
            }
        }

        stage("Update: Kubernetes manifests") {
            steps {
                dir('kubernetes') {
                    sh """
                    sed -i -e 's#wanderlust-backend-beta:.*#wanderlust-backend-beta:${params.BACKEND_DOCKER_TAG}#g' backend.yaml
                    sed -i -e 's#wanderlust-frontend-beta:.*#wanderlust-frontend-beta:${params.FRONTEND_DOCKER_TAG}#g' frontend.yaml
                    """
                }
            }
        }

        stage("Git: Code update and push to GitHub") {
            steps {
                withCredentials([gitUsernamePassword(credentialsId: 'Github-cred', gitToolName: 'Default')]) {
                    sh '''
                    git config user.email "jenkins-bot@automation.local"
                    git config user.name "jenkins-bot"

                    git add .
                    git commit -m "[ci-skip-bot] Updated image tags from Jenkins"
                    git push origin main
                    '''
                }
            }
        }
    }

    post {
        success {
            script {
                emailext attachLog: true,
                    from: '0127cs211132@gmail.com',
                    subject: "Wanderlust Application has been updated and deployed - '${currentBuild.result}'",
                    body: """
                        <html>
                        <body>
                            <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                                <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                            </div>
                            <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                                <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                            </div>
                            <div style="background-color: #87CEEB; padding: 10px; margin-bottom: 10px;">
                                <p style="color: black; font-weight: bold;">URL: ${env.BUILD_URL}</p>
                            </div>
                        </body>
                        </html>
                    """,
                    to: '0127cs211132@gmail.com',
                    mimeType: 'text/html'
            }
        }

        failure {
            script {
                emailext attachLog: true,
                    from: '0127cs211132@gmail.com',
                    subject: "Wanderlust Application build failed - '${currentBuild.result}'",
                    body: """
                        <html>
                        <body>
                            <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                                <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                            </div>
                            <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                                <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                            </div>
                        </body>
                        </html>
                    """,
                    to: '0127cs211132@gmail.com',
                    mimeType: 'text/html'
            }
        }
    }
}
